### ISSUE TITLE
Consider using new uplift-ble library

### ISSUE THREAD

**Issue by librick** [Bennett-Wendorf/hass-uplift-desk#5]
Hello,

I'm a big fan of your Home Assistant integration and the underlying Python library (https://github.com/Bennett-Wendorf/uplift-desk-controller). I reverse-engineered the Uplift Desk App (https://play.google.com/store/apps/details?id=app.android.uplifts&hl=en_US) and decoded the vendor-specific packet structure that Uplift uses.

Originally, I intended to fork your uplift-desk-controller repo and make a PR with new commands. But since I had quite a few changes and documentation, I decided to publish my own library: https://pypi.org/project/uplift-ble/

I've cited your work specifically in a "Prior Work" section of the README: https://github.com/librick/uplift-ble?tab=readme-ov-file#prior-work.

It includes support for newly-discovered commands such as (to name a few):
- `move_to_specified_height`
- `set_units_to_inches`
- `set_units_to_centimeters`
- `set_current_height_as_height_limit_max`
- `set_current_height_as_height_limit_min`
- `clear_height_limit_max`
- `clear_height_limit_min`
- `set_calibration_offset`
- `set_height_limit_max`
- `reset`

It'd be great to have the hass-uplift-desk integration directly use my package and expose additional controls for things like setting the height or changing units. You're also free to incorporate parts of my repo into yours, it's all MIT licensed, just list me as a contributor in the CONTRIBUTORS and/or README file if you think my code is useful.

Thank you for your contributions to open source!

**Comment by librick** [comment]
This is really great feedback and debugging. Thanks!

You definitely found a few bugs. I just pushed a new package version (0.2.0) which should fix most of them:

Bugfixes:
- Replaces the `listen` command's `--address` and `--timeout` local options with global options
- Fixes the off-by-10 error in the get-current-height command

Features:
- Adds a new desk method for returning info from the standard BLE device information service
- Adds input validation for global options `--address` and `--timeout`
- Adds new `--requires-wake` global option to send wake commands before other commands
- Changes move-to-specified height to support dynamic units. E.g., specifiy `27in`, not `27`

I really appreciate the input!

### Responses to your Questions/Observations

#### 1. "I noticed in my own testing..."

I don't know why this works on my end and not on yours. Perhaps it's a difference in control box hardware? I have a V2 Commercial desk rather than the normal V2 desk. Just a theory, but maybe the wake command is needed for power-saving reasons that apply to the normal consumer desks but not the commerical desks? The pictures of the control boxes for each on the [Uplift website](https://www.upliftdesk.com/control-box-for-uplift-standing-desks/?19693=14725&19694=14758) seem identical except for a sticker, maybe there's a hardware difference, maybe not.

I added an optional `--requires-wake` global flag that sends three packets with that `0x00` opcode in a row before whatever subsequent command is specified. Try re-running commands with that flag set (you should see log output that indicates wake packets are being sent).

#### 2. "listen does not adhere to the address parameter..."

This was a bug that's been fixed. As long as you provide global options such as `--address`, `--timeout`, or `--requires-wake` *before* the command you're sending, e.g., before listen, those options should be applied as expected. This should work without scanning:

`python scripts/uplift_ble_cli.py --address XX:XX:XX:XX:XX:XX listen`

substituting your MAC address as appropriate. For now, the `listen` command doesn't support the `--requires-wake` global option; passing that option won't have any effect. I might change this in the future.

#### 3. "listen height measurements are an order of magnitude off..."

This was a bug that's been fixed.

#### 4. "get-current-height fails to retrieve height unless a physical button is pushed, and measurements are off by a factor of 10..."

The first part is strange. This works for me:
```console
python scripts/uplift_ble_cli.py --address XX:XX:XX:XX:XX:XX get-current-height
```
As does this:
```console
python scripts/uplift_ble_cli.py --requires-wake --address XX:XX:XX:XX:XX:XX get-current-height
```

You should see a received packet that has an opcode=0x01. This may merit more investigation.

The off-by-factor-of-10 issue has been fixed.

#### 5. "move-up does nothing..."
Likely a wake issue. Try this:
```console
python scripts/uplift_ble_cli.py --requires-wake --address XX:XX:XX:XX:XX:XX move-up
```

#### 6. "move-down does nothing..."
Likely a wake issue. Try this:
```console
python scripts/uplift_ble_cli.py --requires-wake --address XX:XX:XX:XX:XX:XX move-down
```

#### 7. "request-height-limits uses the same opcode as get-current-height"
Good point. I forget why I did this, I'll have to research this more on my end.

#### 8. "I haven't tried running set-calibration-offset or set-height-limit-max"
Yea it's reasonable to be cautious with these, if you set the calibration offset and height limit to similar values for example the net effect is that your desk won't move. If you want to play around with these in a safer way, check out the Uplift app, which lets you set these settings (and see what their default values are before you change them).

#### 9. "move-to-specified-height doesn't do anything"
You ran into a funny edge case. Internally, I think the desk controller uses millimeters. The value that actually gets sent in the packet for example is in millimeters, so when I wrote the command I just assumed I would treat whatever value a user gave me as millimeters.

Since you specified 40 *millimeters*, you actually specified a height of approx. 1.57 inches. Because this is such a small value (I think technically because this is below the calibration offset of the desk, which is probably ~20"), the desk refuses to move.

I reworked the syntax of this command so now you have to specify a value with units included. It's probably safer this way. Also, 40" is really tall. Try something more reasonable like 26":

```console
python scripts/uplift_ble_cli.py --requires-wake --address XX:XX:XX:XX:XX:XX move-to-specified-height 26in
```

#### 10. "set-current-height-as-height-limit-min doesn't seem to do anything..."
Try with the new `--requires-wake` global option.

#### 11. "set-current-height-as-height-limit-max doesn't seem to do anything..."
Try with the new `--requires-wake` global option.

#### 12. "clear-height-limit-min doesn't seem to do anything..."
This could be a wake issue. Though to test it you first need to be able to set the minimum height limit (either from the CLI or from the Uplift app).

#### 13. "clear-height-limit-max doesn't seem to do anything..."
This could be a wake issue. Though to test it you first need to be able to set the maximum height limit (either from the CLI or from the Uplift app).

#### 14. "stop-movement works fine..."
Glad this works!

#### 15. "I skipped set-units-to-centimeters and set-units-to-inches..."
Fair. I wouldn't recommend playing with these until all other commands work. These also aren't exposed in the Uplift app anymore from what I can tell, though they do work on my desk.

#### 16. "reset has wake issue..."
Try with the new `--requires-wake` global option. Also this doesn't really do anything even for me, it just causes the LED display to flash. It doesn't actually reset internal state/limits as far as I'm aware I think it just cycles the power internally but I'm not sure.

**Comment by Bennett-Wendorf** [comment]
This is great!

As expected, the added wake command(s) fix most of the problems I was having. I also have the V2 commercial frame, so I don't see any reason why they would be behaving differently. For the purposes of the HA integration, does your desk get annoyed if you send it the 0x00 wake commands? Since we can't really detect which desk a user might have, it would be nice if we could just always send that. Also, you don't need to send 3 of the wake commands. I tweaked your code to only send 1, and it works just as well  and you don't even need the delay in between as far as I can tell.

4. This works fine now with the wake command, that seems to have been the only issue with many of these commands. Obviously you wouldn't have a height value from notifications if the command was never actually taken by the desk.

7. When sending that 0x07 op code, my desk returns packets with op codes 0x25, 0x26, 0x27, and 0x28 as well as the 0x01 response with the height. I played around a bit and I'm fairly sure these correspond to the 4 programmed heights that I set on my advanced keypad in order with 0x25 being preset 1, and 0x28 being preset 4! Note that these values report in tenths of the configured units (tenths of inches for me), so I get values of things like 281 for 28.1in. This  makes me wonder if there are ways to set these presets via bluetooth too... At the very least, it would be cool to report them as additional options in the controller that could be usable via the `set-to-specified-height` command!

9. This does work with wake! I had originally used 40 because I assumed the desk would operate in whatever units it was set to display on screen. This is probably my favorite part of what you did!

10-13. These are still super buggy for me, but I don't really think that's your fault. In fact, my Uplift app doesn't work to do this at all most of the time. With your code, I can _sometimes_ get the height min to set properly, but not consistently. It also displays 00.0 on my display for a bit after doing so, but that seems to reset on its own. Clearing these values (both in your code and the Uplift app) says that it worked, but it didn't actually do anything. No idea what's going on with this. I presume it works consistently for you?

**Follow up questions for HA integration:**
1. My library supports internal tracking of the moving status of the desk for long-running ble connections. I do this essentially by tracking time between notification packets so I can reasonably accurately track when the desk is in motion. Is this something you might be interested in adding to your library? Not sure how useful it is in HA, but I'm not crazy about removing features.

2. My library also supports moving the desk to the app's preset sitting and standing heights with op codes 0x05 and 0x06 respectively. To me this is a critical feature as 99.9% of the time, any control I want to do is just to sit down or stand up. I'm curious why you didn't include these? Also, I wonder if there are corresponding op codes for setting those values. Given that they are configured in-app, I'd assume so, but I don't know what they are.

3. More for my own thoughts on this one, but right now my library and the HA integration have to maintain a connection with the desk at all times to retrieve the height notifications. Obviously this isn't optimal as it blocks all other devices from controlling the desk, and I imagine the 24/7 connection for weeks at a time isn't great for power draw or the hardware. Since you seem a bit more experienced with ble than I am, do you have any ideas on how to resolve this?

4. Luckily our two desks are pretty similar, but based on feedback from [this](https://github.com/Bennett-Wendorf/hass-uplift-desk/issues/4) issue on my integration, it seems Uplift changed their protocol drastically at some point. Did you notice anything in your de-compilation of the app that would indicate how this is handled or at least how to tell the desks apart? I suspect this will be a big effort going forward to support this properly.

**Comment by Bennett-Wendorf** [comment]
Hey @AaronHuus,

This is great! I love to see so many other people interested in this and being willing to help out to improve everything!

Looks to me like that firmware revision might be just what we need to handle detection between the two versions and resolved the problems outlined in #4!

One quick note on your PR at a glance: might it be more stable if rather than trying to 100% dynamically find the write and notify characteristics, we just use that broadcasted firmware revision to choose what set of characteristics and commands to use? This is absolutely a topic for further discussion and by no means am I mandating what anyone needs to do here :)

Also, is it safe to assume that all the commands in Eric's `uplift-ble` library work as expected if the right characteristics are used?

**Comment by librick** [comment]
> This is great!
> 
> As expected, the added wake command(s) fix most of the problems I was having. I also have the V2 commercial frame, so I don't see any reason why they would be behaving differently. For the purposes of the HA integration, does your desk get annoyed if you send it the 0x00 wake commands? Since we can't really detect which desk a user might have, it would be nice if we could just always send that. Also, you don't need to send 3 of the wake commands. I tweaked your code to only send 1, and it works just as well and you don't even need the delay in between as far as I can tell.
> 
> 4. This works fine now with the wake command, that seems to have been the only issue with many of these commands. Obviously you wouldn't have a height value from notifications if the command was never actually taken by the desk.
> 5. When sending that 0x07 op code, my desk returns packets with op codes 0x25, 0x26, 0x27, and 0x28 as well as the 0x01 response with the height. I played around a bit and I'm fairly sure these correspond to the 4 programmed heights that I set on my advanced keypad in order with 0x25 being preset 1, and 0x28 being preset 4! Note that these values report in tenths of the configured units (tenths of inches for me), so I get values of things like 281 for 28.1in. This  makes me wonder if there are ways to set these presets via bluetooth too... At the very least, it would be cool to report them as additional options in the controller that could be usable via the `set-to-specified-height` command!
> 6. This does work with wake! I had originally used 40 because I assumed the desk would operate in whatever units it was set to display on screen. This is probably my favorite part of what you did!
> 
> 10-13. These are still super buggy for me, but I don't really think that's your fault. In fact, my Uplift app doesn't work to do this at all most of the time. With your code, I can _sometimes_ get the height min to set properly, but not consistently. It also displays 00.0 on my display for a bit after doing so, but that seems to reset on its own. Clearing these values (both in your code and the Uplift app) says that it worked, but it didn't actually do anything. No idea what's going on with this. I presume it works consistently for you?
> 
> **Follow up questions for HA integration:**
> 
> 1. My library supports internal tracking of the moving status of the desk for long-running ble connections. I do this essentially by tracking time between notification packets so I can reasonably accurately track when the desk is in motion. Is this something you might be interested in adding to your library? Not sure how useful it is in HA, but I'm not crazy about removing features.
> 2. My library also supports moving the desk to the app's preset sitting and standing heights with op codes 0x05 and 0x06 respectively. To me this is a critical feature as 99.9% of the time, any control I want to do is just to sit down or stand up. I'm curious why you didn't include these? Also, I wonder if there are corresponding op codes for setting those values. Given that they are configured in-app, I'd assume so, but I don't know what they are.
> 3. More for my own thoughts on this one, but right now my library and the HA integration have to maintain a connection with the desk at all times to retrieve the height notifications. Obviously this isn't optimal as it blocks all other devices from controlling the desk, and I imagine the 24/7 connection for weeks at a time isn't great for power draw or the hardware. Since you seem a bit more experienced with ble than I am, do you have any ideas on how to resolve this?
> 4. Luckily our two desks are pretty similar, but based on feedback from [this](https://github.com/Bennett-Wendorf/hass-uplift-desk/issues/4) issue on my integration, it seems Uplift changed their protocol drastically at some point. Did you notice anything in your de-compilation of the app that would indicate how this is handled or at least how to tell the desks apart? I suspect this will be a big effort going forward to support this properly.

My desk doesn't get annoyed if I send it the wake commands. I think we can send it wake commands before every command if you were to use my `Desk` implementation within the Home Assistant integration. That said, my general philosophy for the core library (not to be confused with the CLI) was to make it intentionally low-level: no retries, and no sending the wake command from "within" any of the other function calls. So if you use the library, you would just call like `desk.wake()` followed by some delay followed by `desk.move_up()` for example. I did notice that the official app does send commands multiple times in a row sometimes to ensure the desk receives it, usually with a 0.2 second delay between them. I think this is probably a decent idea for idempotent operations. So if you were to implement it you would probably want to send the wake command once or twice with a 0.2 second delay between, followed by a call to send the command you want after that.

5. I noticed the 4-preset height thing too, I think those are the values coming back but they're not documented in the app so I wanted to have more evidence before adding support for them into the library. We can definitely add getters/commands to read those values. I don't know if they're writable though. I can add support for reading their values in the next release though.
10-13. These do tend to work for me, but note that there are some safeguards with the desk firmware itself I think where if you try and send a value outside of a reasonable range, the command will be silently ignored. Like if you try to set too low of a value or set max height lower than the offset value I think the command will silently fail.

Answers to follow-up questions:
1. I can definitely add support for this. Right now I just log notifications but I can allow developers to register callbacks for specific things like height. I can add this in the next release.
2. I'm not sure why I didn't support opcodes 0x05 and 0x06. I'll add these in the next release.
3. I don't have a solution for this. If you want to have real-time height notifications, no matter what that implies that the Bluetooth stack on the desk is transmitting, which implies that it's using power. Personally I'm not worried about the power use. Also, blocking other connections to the desk might be a good thing considering it ships without any authorization and controls a big heavy object. If you do want to manage the lifecycle of the Desk app (other than using a `with` statement), it does support `connect()` and `disconnect()` methods.
4. Check out my notes on the PR here: https://github.com/librick/uplift-ble/pull/2. I've discussed compatibility more there

Thanks for following up on this. Apologies for the delay, last week was finals week. It's good to be back to working on PRs :) I'll get a new release out soon.

**Comment by librick** [comment]
>My library also supports moving the desk to the app's preset sitting and standing heights with op codes 0x05 and 0x06 respectively. To me this is a critical feature as 99.9% of the time, any control I want to do is just to sit down or stand up. I'm curious why you didn't include these? Also, I wonder if there are corresponding op codes for setting those values. Given that they are configured in-app, I'd assume so, but I don't know what they are.

Also, funny thing about this. I wasn't really sure what you were talking about, but I tested these out on my end:
- Sending opcode 0x05 with an empty payload causes the desk to move to whatever is programmed as preset 1
- Sending opcode 0x06 with an empty payload causes the desk to move to whatever is programmed as preset 2.

I just tested this now, setting my presets manually to various values and successfully moving to those heights solely by sending 0x05 and 0x06.

Further, I'm pretty sure the Uplift app "fakes" the "Set sit/stand heights" settings page in the sense that it doesn't actually save those to the controller at all. The app just saves those values in the app's setting storage on your phone. When you click "Sit" or "Stand" from the main screen, I'm pretty sure it just sends opcode 0x1B (`move_to_specified_height`) with the relevant saved value. If you wanted to implement in the Home Assistant integration, one way is to let users specify values for these, save them in the integrations settings, and call `move_to_specified_height` under-the-hood.

Can you try sending 0x05 and 0x06 to the desk after changing presets 1-4 (well, specifically presets 1-2) via the physical desk buttons and see if that changes the heights to which 0x05 and 0x06 navigate?

**Comment by librick** [comment]
> Perfect, thanks for the deep dive! The main callout from that other thread you identified is the missing support for 0xFF12 service Id. If that can be added to either that new library, or whatever library ends up being used for `hass-uplift-desk` that would be immensely helpful.
> 
> If I can help in testing or investigation at all with my desk, let me know. Thanks for the support with this!

Since the implementation of the two revisions looks similar, I'll probably start by adding support for that 0xFF12 service UUID for desk discovery in the next release, but I'll keep the same characteristics (0xFE61 and 0xFE62) in use regardless because it looks like the app keeps those constant, irrespective of whether the service is 0xFE60 or 0xFF12. Once I have that release out, you can try each command and document any that behave unexpectedly. Then I can cross-reference that with the app source code and get it supported. Happy to help, thanks for the info! :)

**Comment by librick** [comment]
Also as a warning, avoid testing opcode 0x12. It does something that messes with the desk's speed and puts it in a very, very strange state. I'm still debugging it.

**Comment by Bennett-Wendorf** [comment]
> Answers to follow-up questions:
> 
>     1. I can definitely add support for this. Right now I just log notifications but I can allow developers to register callbacks for specific things like height. I can add this in the next release.
> 
>     2. I'm not sure why I didn't support opcodes 0x05 and 0x06. I'll add these in the next release.
> 
>     3. I don't have a solution for this. If you want to have real-time height notifications, no matter what that implies that the Bluetooth stack on the desk is transmitting, which implies that it's using power. Personally I'm not worried about the power use. Also, blocking other connections to the desk might be a good thing considering it ships without any authorization and controls a big heavy object. If you do want to manage the lifecycle of the Desk app (other than using a `with` statement), it does support `connect()` and `disconnect()` methods.
> 
>     4. Check out my notes on the PR here: [Support dynamically selecting the command and notify characteristics librick/uplift-ble#2](https://github.com/librick/uplift-ble/pull/2). I've discussed compatibility more there
> 
> 
> Thanks for following up on this. Apologies for the delay, last week was finals week. It's good to be back to working on PRs :) I'll get a new release out soon.

Awesome! I think that probably covers everything I deem critical to swap the HA integration over to this library instead. At this point, I just really want to be at a state where we have feature parity, so once you get 1 and 2 added, that will be true. I'll keep an eye out for the release of yours and we'll go from there. I think it'll make the most sense to develop v2 and release with the swap to your library plus a few new features at the same time.

For #3, I'm not too worried, I just thought maybe you knew something I didn't. I'm also not too concerned about the power draw, and you're totally write that the security on these things is abysmal. 

Compatibility is always a great thing to have, and it sounds like your discussion over on pull 2 has gotten further than any look I've had so far, which reinforces that using your library going forward is probably the way to go.

Keep me posted on your release and we'll go from there!

**Comment by Bennett-Wendorf** [comment]
> > My library also supports moving the desk to the app's preset sitting and standing heights with op codes 0x05 and 0x06 respectively. To me this is a critical feature as 99.9% of the time, any control I want to do is just to sit down or stand up. I'm curious why you didn't include these? Also, I wonder if there are corresponding op codes for setting those values. Given that they are configured in-app, I'd assume so, but I don't know what they are.
> 
> Also, funny thing about this. I wasn't really sure what you were talking about, but I tested these out on my end:
> 
>     * Sending opcode 0x05 with an empty payload causes the desk to move to whatever is programmed as preset 1
> 
>     * Sending opcode 0x06 with an empty payload causes the desk to move to whatever is programmed as preset 2.
> 
> 
> I just tested this now, setting my presets manually to various values and successfully moving to those heights solely by sending 0x05 and 0x06.
> 
> Further, I'm pretty sure the Uplift app "fakes" the "Set sit/stand heights" settings page in the sense that it doesn't actually save those to the controller at all. The app just saves those values in the app's setting storage on your phone. When you click "Sit" or "Stand" from the main screen, I'm pretty sure it just sends opcode 0x1B (`move_to_specified_height`) with the relevant saved value. If you wanted to implement in the Home Assistant integration, one way is to let users specify values for these, save them in the integrations settings, and call `move_to_specified_height` under-the-hood.
> 
> Can you try sending 0x05 and 0x06 to the desk after changing presets 1-4 (well, specifically presets 1-2) via the physical desk buttons and see if that changes the heights to which 0x05 and 0x06 navigate?

Weird, you're totally right! I think I always had my sit/stand presets in the app configured to presets 1 and 2 anyway, so I didn't notice the difference. Honestly, I think the direct use of the presets from the controller makes more sense anyway, though it does make me wonder what happens if someone has a keypad without the memory features. We can cross that particular bridge when we come to it.

I think the best way to implement this in the integration is going to be just offering buttons 1-4 for each of the presets and we can abstract away any logic from the user for what command it actually runs. Whether that means we just always use the `move-to-specified-height` or if we use op codes 0x05 and 0x06 in some cases, I'm not sure. Thoughts? Either way, I think adding the commands to your library makes most sense. Keeping it as a source of truth for everything we know about the way these operate seems like a good idea.

Given that we have the `move-to-specified-height` now, it's definitely worth consideration for letting users set potentially arbitrary numbers of presets for themselves, but I think this falls under the future enhancement category rather than something I'd want to do for v2.

**Comment by Bennett-Wendorf** [comment]
I created a project over on [Bennett-Wendorf/hass-uplift-desk](https://github.com/Bennett-Wendorf/hass-uplift-desk) that can be found [here](https://github.com/users/Bennett-Wendorf/projects/10/views/1) to help track what needs to be done on the integration for this to be a reality. Feel free to let me know if you have any suggestions on what else can be added. As of right now, I'll get started on the migration if I have time, pending an update to Eric's library before I push a version out to HACS. Thanks again everyone for putting so much time into this!

**Comment by librick** [comment]
### New Library Version, v0.3.0

I pushed an update to the uplift-ble library, v0.3.0. I encourage everyone to glance over the commit messages, PRs, and release notes. The biggest new features are:
- Ability to register callbacks
- Ability to navigate to desk presets 1 and 2 as saved via the physical keypad
- Support for service UUID 0xFF12. This is experimental but should work for basic commands
- New `get_ble_gap_values` and `get_ble_dis_values` methods

New callbacks:
- `on_notification_height`
- `on_notification_rst`
- `on_notification_calibration_height`
- `on_notification_height_limit_max`

### On Height Preset 1-4 Notifications

@Bennett-Wendorf thanks for the info on the preset readings. Unfortunately I think we are getting values in different units. Perhaps we have different keypads? I'm using this one, which I think is a bit older than the ones currently sold:

<img width="1000" height="538" alt="Image" src="https://github.com/user-attachments/assets/d8275078-a07c-4c3f-b622-c0d0529b8dbf" />

The newer one is more square:

<img width="2033" height="2032" alt="Image" src="https://github.com/user-attachments/assets/95671d5f-897a-4bfe-a7ca-60bd547b553d" />

I think my keypad saves presets as encoder steps, where each encoder step is ~0.00254", plus some offset whose origin is currently unknown to me.

If we did want to support notifications for preset heights, we might have to add an argument to the `Desk` class's constructor. Something like `preset_height_scalar` that takes an enum that describes known scaling functions or something, and then expose that as a setting within Home Assistant. Not super pretty but not infeasible. If this is related to differences between keypads, I'm not optimistic that we could determine this dynamically based on the behavior of the BLE adapter. I also generally want to avoid probabilistic conversions (like changing the conversion algorithm based on whether a value seems too big to be a height in inches, for example) as I think doing so risks making the library's behavior unpredictable.

All of this also makes me feel like it's unlikely that the BLE adapter itself can set the presets in the first place. I'll keep poking around at the unmapped opcodes though.

### Notes for Implementation

Some off-the-cuff notes/questions if you go forward with implementing the `uplift-ble` library:

1. My preference would be to remove the `requires_wake` parameter from the Desk constructor and have higher-level consumers (i.e., you/Home Assistant) be responsible for sending wake commands and sending retries. I originally implemented this way so you could quickly validate that wake was causing issues with the other commands. Removing it would keep the `Desk` API lean and limit internal state on my end. If you agree, I'll probably deprecate/remove the `requires_wake` parameter from the constructor and require you to call the `wake` command in some wrapper that you implement in the Home Assistant integration code. (The CLI that I ship can still support a `--requires-wake` option, but it would work by wrapping the invocation of `Desk` commands, not giving it a parameter). Good idea? Bad idea?
2. Similarly to the points made in (1), I don't implement too much state around the current height or whether the desk is moving. I see the library really as a thin interface in front of the desk, not a way to track its state in general. So I gave you an `on_notification_height` callback that you can set, but if you want to retain the boolean "is desk moving" state in Home Assistant I think this should be the responsibility of the Home Assistant integration.
3. Avoid using the CLI at all for Home Assistant purposes. It's really just intended as a way to test things. Everything should be done via the core `DeskScanner` and `Desk` classes. See the Usage example in the README.
4. This is minor, but I've moved from using "RST" instead of "ASR" to refer to the reset (RST) state that the desk gets in sometimes. I originally used "ASR" because "RST" looks like "ASr" [sic] on my display. I've moved to referring to this three-letter reset state as RST consistently now. You also have a shiny new callback, `on_notification_rst`, that you can use in the integration to show the user that their desk is in an error state.
5. Consider adding retries when you send commands for idempotent commands. The app uses a default delay of 0.2 seconds. This might help reliability for various commands within the integration.

### Follow Up Questions
1. Are there any other features of the library that are must-haves before it's usable by your integration?
2. Are you okay if I remove the `requires_wake` parameter from the constructor and push that responsibility upstream?
3. Can you use the `reset()` method and post the notification that starts with `f2f212`? Sending a command with opcode 0x12 is dangerous but the `reset()` method isn't. I'm trying to figure out what its default value is.
4. What model of keypad do you use?

**Comment by Bennett-Wendorf** [comment]
Yeah, different keypads seems the likely culprit. I am using the newer one (the angled one to be specific, but I doubt that matters). That does concern me for the use of op codes 0x05 and 0x06 and notifications 0x25-0x28. Obviously this poses a challenge for our two models for sure, but one that can be overcome with some sort of setup parameter. I think that could be done pretty easily during the config flow of the integration as long as we can document well enough what we expect. My bigger concern is what happens to these values for a user with the more basic two-button keypad or the paddle one that doesn't have presets. We might just have to wait and see if someone comes along to test it for us, though I suspect that user base is a fair bit smaller.

## Answers to follow up questions
1. I don't think so. I'm starting work on the migration of the integration today, and I'm hoping to have a beta version using your library soon. I think we've covered everything that my library did already, so at least for feature parity I think we're good. My plan is to get to feature parity before releasing a beta, and then continue adding a couple of the new features before fulling releasing v2 of the integration. I'll keep you posted on the progress of this for testing purposes, and I'll for sure let you know if I come across any critical shortcomings.
2. Yeah, I think handling that upstream is fine. Language from HA is to handle as much as possible in a python library and to essentially use the integration as a shell for translating that logic into HA constructs, but I think handling the wake from the integration still follows the spirit of these guidelines.
3. For completeness, I'll include all the notification packets I get back after running a reset in the format `<opcode> => <payload> (<comments>)`

```
0xFE => 0x (seems to be something strange here. Probably just your logic isn't expecting an empty payload or something)
0x0D => 0x02
0x0E => 0x01
0x0F => 0x0003
0x10 => 572mm (~22.3in) (Still not super clear on what this is, so I can't comment on whether it's correct )
0x11 => 667mm (~26.0in) (Something is strange here for sure. In fact, this can't directly be the height max because my height min is set higher than this. Even adding the calibration offset to it doesn't seem quite right, so I'm not quite sure what's going on here. My actual height max is ~48.7in)
0x12 => 0x0082
0x13 => 0x32
0x14 => 0x4B
0x15 => 0x2D
0x16 => 0x64
0x17 => 0x01
0x18 => 0x01
0x19 => 0x00
0x1C => 0x0A
0x1D => 0x01
0x1E => 0x01
0x1A => 0x00
0x23 => 0x2192CB04
```

**Comment by Bennett-Wendorf** [comment]
Ok, I did come up with a couple things for implementation. While I do have workarounds for all of these, fixes to your library would make implementation a bit cleaner.

1. I need a way to set the timeout on the Bleak Client. HA gets pretty finicky when it comes to this value, and recommend setting it to at least 10 seconds. I've had good luck with 15. Ideally I think this would be an optional parameter to the `Desk` constructor.
2. I don't have a use for it yet, but I could see future potential for needing multiple callbacks of each type. I'd prefer if your library maintained a list of callbacks of each type instead of just a single one.
3. Again, not critical, but especially if there's a list of callbacks it would be very handy to have a simple method to register these callbacks instead of having to set the properties manually.
4. Logs from the library probably shouldn't be info level for things like notification packets. When debugging HomeAssistant these surface as info logs which will probably piss off other HA devs. (HA actually throws a warning about this if a library logs too often)

Also, FYI, some of the links on your PyPi page don't work (Homepage and Issues). They appear to reference `uplift_ble` instead of `uplift-ble`

Finally, v2.0.0-beta.0 has been released! It should get to feature parity using your library in place of mine. I did end up just dropping the moving sensor since it probably isn't that useful anyway and also reduces the amount of state that has to be maintained in either the library or integration. To test it out, go to the HACS page for the integration, navigate to the three dots, and select redownload and "Need a different version?". If you have any issues, feel free to mention them here or open up a new issue and make sure to mention v2.0.0-beta.0. Happy testing!

**Comment by librick** [comment]
> That's odd. My environment installed 2.0.0-beta.0 just fine. I can take a closer look through your stack trace when I have some time.

Perhaps you installed some of the dependencies, such as `typer`, manually?
My Home Assistant Core version: 2025.8.1
My Home Assistant Operating System version: 16.1

I just shipped package version 0.4.0, which, among other things, removes `typer` as a core dependency.
In theory, `uplift-ble` has only one dependency now, `"bleak>=1.0.1"`. I'm hoping that solves the problem.

Enjoy the [release](https://github.com/librick/uplift-ble/releases/tag/v0.4.0) :)

**Comment by Bennett-Wendorf** [comment]
No clue why we were seeing different behavior. I had a pretty new HAOS install with the same version as you and I wouldn't have installed any dependencies custom, unless some other integration did it.

Regardless I pushed `v2.0.0-beta.1` that uses uplift-ble v0.4.0. Let me know how that goes!

**Comment by Bennett-Wendorf** [comment]
I also just now noticed that v2.0.0-beta.1 and uplift-desk v0.4.0 breaks the monitoring of desk height completely for me. Regardless of movement from HA or the desk's hardware control panel, no height updates are received by HA. Is anyone else seeing this?

**Comment by arh-au** [comment]
Hi, happy to try and help here with Australian Desky unit, however I might need a bit of hand-holding as I'm still learning HA, etc.  It's been 30 years since I coded anything ;-)

**Comment by MrPostHipster** [comment]
I stumbled on this thread trying to integrate my own Uplift V2 Desk with BT Dongle into HA.  After updating the correct service_uuid in manifest.json I can see my desk in HA, but connecting to the device throws errors.

Based on this thread, I updated to the  v2.0.0.-beta.1 package, but I still get a `bleak.exc.BleakCharacteristicNotFoundError: Characteristic 0000fe62-0000-1000-8000-00805f9b34fb was not found!` error.   I'm not a BT expert, but from reading the thread above it appears that this characteristic is working reliably for others?  I plan to probe my desk via gatttool to get the exposed characteristics, but I want to make sure I'm missing something obvious higher up the dependency chain.

**Comment by cbusillo** [comment]
@Bennett-Wendorf is this ready to be closed, or are you waiting for the full release?  Are there more things you want to clean up first?  Let me know if I can help.

**Comment by Bennett-Wendorf** [comment]
@cbusillo, I think everything in this issue is done, but I'm waiting to close it till a full release. Most likely once the last PR your bot has open is merged, I'll push another beta for a week or so, and then go for a full v2.0.0 release.

**Comment by Bennett-Wendorf** [comment]
Just dropped beta 5. I intend for it to be the final beta of the v2 release, and if all goes well for the next week or so I'll release a full v2 version!
